interface ICocktail {
  idDrink: string;
  strDrink: string;
  strDrinkAlternate?: string;
  strDrinkES?: string;
  strDrinkDE?: string;
  strDrinkFR?: string;
  ["strDrinkZH-HANS"]?: string;
  ["strDrinkZH-HANT"]?: string;
  strTags: string;
  strVideo?: string;
  strCategory: string;
  strIBA: string;
  strAlcoholic: string;
  strGlass: string;
  strInstructions: string;
  strInstructionsES?: string;
  strInstructionsDE: string;
  strInstructionsFR?: string;
  ["strInstructionsZH-HANS"]?: string;
  ["strInstructionsZH-HANT"]?: string;
  strDrinkThumb: string;
  strIngredient1: string;
  strIngredient2: string;
  strIngredient3: string;
  strIngredient4?: string;
  strIngredient5?: string;
  strIngredient6?: string;
  strIngredient7?: string;
  strIngredient8?: string;
  strIngredient9?: string;
  strIngredient10?: string;
  strIngredient11?: string;
  strIngredient12?: string;
  strIngredient13?: string;
  strIngredient14?: string;
  strIngredient15?: string;
  strMeasure1: string;
  strMeasure2: string;
  strMeasure3: string;
  strMeasure4?: string;
  strMeasure5?: string;
  strMeasure6?: string;
  strMeasure7?: string;
  strMeasure8?: string;
  strMeasure9?: string;
  strMeasure10?: string;
  strMeasure11?: string;
  strMeasure12?: string;
  strMeasure13?: string;
  strMeasure14?: string;
  strMeasure15?: string;
  strCreativeCommonsConfirmed: string;
  dateModified: string;
}

export class Cocktail implements ICocktail {
  idDrink: string;
  strDrink: string;
  strDrinkAlternate?: string;
  strDrinkES?: string;
  strDrinkDE?: string;
  strDrinkFR?: string;
  strDrinkZH_HANS?: string;
  strDrinkZH_HANT?: string;
  strTags: string;
  strVideo?: string;
  strCategory: string;
  strIBA: string;
  strAlcoholic: string;
  strGlass: string;
  strInstructions: string;
  strInstructionsES?: string;
  strInstructionsDE: string;
  strInstructionsFR?: string;
  strInstructionsZH_HANS?: string;
  strInstructionsZH_HANT?: string;
  strDrinkThumb: string;
  strIngredient1: string;
  strIngredient2: string;
  strIngredient3: string;
  strIngredient4?: string;
  strIngredient5?: string;
  strIngredient6?: string;
  strIngredient7?: string;
  strIngredient8?: string;
  strIngredient9?: string;
  strIngredient10?: string;
  strIngredient11?: string;
  strIngredient12?: string;
  strIngredient13?: string;
  strIngredient14?: string;
  strIngredient15?: string;
  strMeasure1: string;
  strMeasure2: string;
  strMeasure3: string;
  strMeasure4?: string;
  strMeasure5?: string;
  strMeasure6?: string;
  strMeasure7?: string;
  strMeasure8?: string;
  strMeasure9?: string;
  strMeasure10?: string;
  strMeasure11?: string;
  strMeasure12?: string;
  strMeasure13?: string;
  strMeasure14?: string;
  strMeasure15?: string;
  strCreativeCommonsConfirmed: string;
  dateModified: string;

  // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
  constructor(data: any) {
    this.idDrink = data.idDrink;
    this.strDrink = data.strDrink;
    this.strDrinkAlternate = data.strDrinkAlternate;
    this.strDrinkES = data.strDrinkES;
    this.strDrinkDE = data.strDrinkDE;
    this.strDrinkFR = data.strDrinkFR;
    this.strDrinkZH_HANS = data["strDrinkZH-HANS"];
    this.strDrinkZH_HANT = data["strDrinkZH-HANT"];
    this.strTags = data.strTags;
    this.strVideo = data.strVideo;
    this.strCategory = data.strCategory;
    this.strIBA = data.strIBA;
    this.strAlcoholic = data.strAlcoholic;
    this.strGlass = data.strGlass;
    this.strInstructions = data.strInstructions;
    this.strInstructionsES = data.strInstructionsES;
    this.strInstructionsDE = data.strInstructionsDE;
    this.strInstructionsFR = data.strInstructionsFR;
    this.strInstructionsZH_HANS = data["strInstructionsZH-HANS"];
    this.strInstructionsZH_HANT = data["strInstructionsZH-HANT"];
    this.strDrinkThumb = data.strDrinkThumb;
    this.strIngredient1 = data.strIngredient1;
    this.strIngredient2 = data.strIngredient2;
    this.strIngredient3 = data.strIngredient3;
    this.strIngredient4 = data.strIngredient4;
    this.strIngredient5 = data.strIngredient5;
    this.strIngredient6 = data.strIngredient6;
    this.strIngredient7 = data.strIngredient7;
    this.strIngredient8 = data.strIngredient8;
    this.strIngredient9 = data.strIngredient9;
    this.strIngredient10 = data.strIngredient10;
    this.strIngredient11 = data.strIngredient11;
    this.strIngredient12 = data.strIngredient12;
    this.strIngredient13 = data.strIngredient13;
    this.strIngredient14 = data.strIngredient14;
    this.strIngredient15 = data.strIngredient15;
    this.strMeasure1 = data.strMeasure1;
    this.strMeasure2 = data.strMeasure2;
    this.strMeasure3 = data.strMeasure3;
    this.strMeasure4 = data.strMeasure4;
    this.strMeasure5 = data.strMeasure5;
    this.strMeasure6 = data.strMeasure6;
    this.strMeasure7 = data.strMeasure7;
    this.strMeasure8 = data.strMeasure8;
    this.strMeasure9 = data.strMeasure9;
    this.strMeasure10 = data.strMeasure10;
    this.strMeasure11 = data.strMeasure11;
    this.strMeasure12 = data.strMeasure12;
    this.strMeasure13 = data.strMeasure13;
    this.strMeasure14 = data.strMeasure14;
    this.strMeasure15 = data.strMeasure15;
    this.strCreativeCommonsConfirmed = data.strCreativeCommonsConfirmed;
    this.dateModified = data.dateModified;
  }
}
